name: ticket
description: ticket
title: "[TICKET]: "
labels: ["ticket"]
assignees: ["fxpw"]
body:
  - type: input
    id: client
    attributes:
      label: Клиент
      description: Укажите клиента и контакты для связи
      placeholder: Например A1(почта) или ссылку на Telegram
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Версия
      description: Укажите версию продукта
      placeholder: 1.0.0 ... 3.0.0
    validations:
      required: true

  - type: textarea
    id: cwow
    attributes:
      label: "## Законченная работа сотрудника"
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
